config/routes.rb
Tastell::Application.routes.draw do

  root to: 'places#index'

  match '/auth/:provider/callback', to: 'authentications#create'
  match '/auth/failure', to: 'authentications#failure'

  resources :places, only: [:index, :show] do
    get :map, on: :collection
    get :list, on: :collection
    resources :comments, on: :collection, only: :index, controller: 'place/comments'
  end
  resources :orders, only: [:create] do
    get :check, on: :member
  end

  resources :users, only: [:index]
  resource :profile, only: [:show, :edit, :update]
  resources :authentications, only: [:new, :create] do
    get :failure, on: :collection
    delete :sign_out, on: :collection
  end

  resources :accounts, only: [] do
    get :login, on: :collection
    post :authenticate, on: :collection
    delete :logout, on: :collection
  end


  namespace :account do
    resources :places do
      get :description, on: :member

      resources :place_requisites, only: [:edit, :update]
      resources :photos, only: [:index, :create, :destroy]
    end
  end

  namespace :admin do
    resources :places, only: [:index, :show] do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :users
  end

  resources :pages, only: [] do
    get :about, on: :collection
    get :venues, on: :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :avatar, :first_name, :last_name
  attr_accessible :fake

  mount_uploader :avatar, UserAvatarUploader

  has_many :orders
  has_one :authentication

  acts_as_api
  include ApiV1::User

  scope :fakes, where(fake: true)

  def full_name
    "#{first_name} #{last_name}"
  end

  def avatar_mini
    avatar_url(:mini)
  end

  def to_s
    full_name
  end

  # @param [Order] order
  def create_order(order)
    return false unless can_create_order?(order.place)
    order.save
  end

  # @param [Place] place
  def can_create_order?(place)
    orders.with_place(place).confirmed.today.empty?
  end

  def fake?
    fake
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  layout 'admin'

  def index
    @users = User.fakes.order('id desc')
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.fake = true

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/views/admin/users/_form.html.haml
= simple_form_for user, url: url do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :avatar
  = f.submit

app/views/admin/users/edit.html.haml
%legend
  Редактировать пользователя

= render partial: 'admin/users/form', locals: {user: @user, url: admin_user_path(@user.id)}

app/views/admin/users/index.html.haml
%legend
  Фейковые пользователи
  %a.btn{href: new_admin_user_path, style: 'float: right'}
    Добавить


%table{width: '100%'}
  - @users.each do |user|
    %tr
      %td{width: 70}
        = image_tag user.avatar_mini
      %td{width: 200}
        = user.full_name
      %td
        = link_to 'редактировать', edit_admin_user_path(user.id)

app/views/admin/users/new.html.haml
%legend
  Добавить пользователя

= render partial: 'admin/users/form', locals: {user: @user, url: admin_users_path}