config/routes.rb
Tastell::Application.routes.draw do

  root to: 'places#index'

  match '/auth/:provider/callback', to: 'authentications#create'
  match '/auth/failure', to: 'authentications#failure'

  resources :places, only: [:index, :show] do
    get :map, on: :collection
    get :list, on: :collection
    resources :comments, on: :collection, only: :index, controller: 'place/comments'
  end
  resources :orders, only: [:create] do
    get :check, on: :member
  end

  resources :users, only: [:index]
  resource :profile, only: [:show, :edit, :update]
  resources :authentications, only: [:new, :create] do
    get :failure, on: :collection
    delete :sign_out, on: :collection
  end

  resources :accounts, only: [] do
    get :login, on: :collection
    post :authenticate, on: :collection
    delete :logout, on: :collection
  end


  namespace :account do
    resources :places do
      get :description, on: :member

      resources :place_requisites, only: [:edit, :update]
      resources :photos, only: [:index, :create, :destroy]
    end
  end

  namespace :admin do
    resources :places, only: [:index, :show] do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :users
  end

  resources :pages, only: [] do
    get :about, on: :collection
    get :venues, on: :collection
  end

end

app/views/layouts/_footer.html.haml
#footer
  = '&copy'.html_safe
  2013
  .phone{style: 'font-size: 13px; color: #000'}
    Чтобы связаться с нами, просто позвоните по номеру:
    8 (495) 792-89-59.

app/views/layouts/_header.html.haml
#header-inside

  #logo
    %a{href: root_path}
      = image_tag('logo.png')

  #search-and-links
    .first-row
      .about
        Кафе и рестораны, о которых говорят
      %ul.header-links
        %li{class: (params[:controller] == 'pages' and params[:action] == 'about') ? 'picked' : ''}
          %a{href: about_pages_path} О проекте
        %li{class: (params[:controller] == 'pages' and params[:action] == 'venues') ? 'picked' : ''}
          %a{href: venues_pages_path} Заведениям

        %li
          - if user_logged_in?
            = link_to 'Выйти', sign_out_authentications_path, method: :delete
          - else
            %a.oauth-link{href: '/auth/vkontakte'} Войти

    .last-row
      %form.search{action: places_path, method: :get}
        %input{name: 'search[string]',
           autocomplete: :off,
           value: ((params[:search] && params[:search][:string]) ? params[:search][:string] : nil),
           placeholder: 'Напишите любое слово, имеющее отношение к заведению ( название, адрес )'}

app/views/layouts/_metrika.mobile.erb
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter19904464 = new Ya.Metrika({id:19904464, clickmap:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/19904464" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

app/views/layouts/_new_header.html.haml
#logo
  %a{href: root_path}
    = image_tag('logo_white.png')
%form#search{action: places_path, method: :get}
  %input{name: 'search[string]',
             autocomplete: :off,
             value: ((params[:search] && params[:search][:string]) ? params[:search][:string] : nil),
             placeholder: 'Поиск'}

app/views/layouts/account.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    "account", :media => "all"
    = javascript_include_tag "account"
  %body

    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            %li
              = link_to 'Заведения', account_places_path
          %ul.nav.pull-right
            %li
              - if account_signed_in?
                = link_to 'Выйти', logout_accounts_path, method: :delete
              - else
                = link_to 'Войти', login_accounts_path




    .container
      .row
        .span12
          = yield
          = yield :scripts

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', :media => 'all'
    = javascript_include_tag 'admin'
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            %li
              = link_to 'Заведения', admin_places_path
            %li
              = link_to 'Пользователи', admin_users_path

    .container
      .row
        .span12
          = yield
          = yield :scripts

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    "map", :media => "all"
    = javascript_include_tag "http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU"
    = javascript_include_tag "map"
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят'
  %body
    #header
      .container
        = render partial: 'layouts/new_header'

    #for-restoraunts
      Вы владелец заведения? Узнайте о проекте
      %a{href: about_pages_path} подробнее
    #about
      .container
        .banner


    #places
      %h1
        Наши заведения
      #places-list

      .btn#load-more-places
        Показать еще



    #map-container
      %h1
        Заведения на карте
      #map

        .map-widget
          .header
            Популярные заведения
          .places-widget#popular-place-list

    #last-comments
      .container
        %h1
          Последние отзывы
      .comments-widget
        .comments
          - Order.only_moderated.order('id desc').includes(:user).includes(:place).limit(15).each do |comment|
            .comment
              .avatar
                = image_tag comment.user.avatar_url(:mini)
              .content
                .top
                  .name
                    = comment.user.full_name
                    %small{style: 'font-size: 12px; font-style: italic;'}
                      ( о ресторане
                      = link_to comment.place.name, place_path(comment.place)
                      )
                  .date
                    = l comment.created_at, format: :dayMonth
                .text
                  = comment.content

    #footer
      &copy;
      tastle.ru 2013.
      .phone{style: 'font-size: 13px; color: #000'}
        Чтобы связаться с нами, просто позвоните по номеру:
        8 (495) 792-89-59.

app/views/layouts/application.mobile.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    %meta{:content => 'width=device-width, initial-scale=1, maximum-scale=1', :name => 'viewport'}
    = stylesheet_link_tag    'mobile', media: 'all'
    = javascript_include_tag 'mobile'
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят'
  %body
    #wrapper
      #header
        .title
          %a{href: root_path}
            = image_tag 'mob_logo.png'
      .hr-shadow
      - if user_logged_in?
        #user-info
          .avatar
            = image_tag current_user.avatar_url(:mini)
          .name
            = current_user.full_name


      #content
        .padder
          = yield

    = render partial: 'layouts/metrika'

app/views/layouts/application_place.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU'
    = javascript_include_tag 'application'
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят', reverse: true
  %body
    #header
      .wrapper
        = render partial: 'layouts/new_header'

    .wrapper
      = yield
    = render partial: 'layouts/footer'
    = render partial: 'layouts/metrika'

app/views/layouts/authentication.html.haml
!!! 5
%html
  %head
    %title
      GURMAP - бесплатные скидки в рестораны и кафе.
    = javascript_include_tag "authentication"
  %body
    = yield

app/views/layouts/map.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'map', :media => 'all'
    = javascript_include_tag 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU'
    = javascript_include_tag 'map'
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят'
  %body
    #header
      .container
        = render partial: 'layouts/new_header'

    #for-restoraunts
      Вы владелец заведения? Узнайте о проекте
      %a{href: about_pages_path} подробнее
    #about
      .container
        .banner


    #places
      %h1
        Наши заведения
      #places-list

      .btn#load-more-places
        Показать еще



    #map-container
      %h1
        Заведения на карте
      #map

        .map-widget
          .header
            Популярные заведения
          .places-widget#popular-place-list

    #last-comments
      .container
        %h1
          Последние комментарии
      .comments-widget
        .comments
          - Order.order('id desc').includes(:user).includes(:place).each do |comment|
            .comment
              .avatar
                = image_tag comment.user.avatar_url(:mini)
              .content
                .top
                  .name
                    = comment.user.full_name
                    к заведению
                    = link_to comment.place.name, place_path(comment.place)
                  .date
                    = l comment.created_at, format: :dayMonth
                .text
                  = comment.content





    #footer
      &copy;
      tastle.ru 2013.

    = yield

app/views/layouts/metrika.mobile.erb
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter19904464 = new Ya.Metrika({id:19904464, clickmap:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/19904464" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

app/views/layouts/page.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU'
    = javascript_include_tag 'application'
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят'
  %body{style: 'background: #fff'}
    #header
      .container
        = render partial: 'layouts/new_header'

    .container
      = yield

app/views/layouts/search.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'map', :media => 'all'
    = javascript_include_tag 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU'
    = javascript_include_tag 'map'
    = display_meta_tags site: 'Тэстл. Кафе и рестораны, о которых говорят'
  %body{style: 'background: #fcfcfc'}
    #header
      .container
        = render partial: 'layouts/new_header'

    = yield